<?php

/**
 * Main landing view.
 *
 * @copyright  2012 iTradeTunes Inc.
 * @version    $Id$
 * @since      File available since release 1.0.0.0
 */

?>

<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %siTradeTunes%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('iTradeTunes makes it easy to trade CDs right from your iTunes library.') ?></p>
    <p><a class="btn btn-success btn-large" href="#" target="_blank"><?php echo $this->translate('Watch a Video') ?> &raquo;</a></p>
</div>

<div class="row">
    <div class="span4">
        <h2><?php echo $this->translate('Register') ?></h2>
        <p><?php echo $this->translate('Register to upload your CD collection to iTradeTunes or contact other users about CDs you would like to buy or trade.') ?></p>
        <p><a class="btn btn-success" href="<?php echo $this->url('member', array('action' => 'join')); ?>"><?php echo $this->translate('Register User') ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Install') ?></h2>
        <p><?php echo $this->translate('Download and install the iTradeTunes application for Mac OS X or Windows to upload your imported albums that you wish to sell or trade.') ?></p>
        <p><a class="btn btn-success" href="#" target="_blank"><?php echo $this->translate('Download iTradeTunes') ?> &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Browse') ?></h2>
        <p><?php echo $this->translate('Browse our extensive collection of CDs that were uploaded by users.') ?></p>
       <p><a class="btn btn-success" href="#"><?php echo $this->translate('Browse Albums') ?> &raquo;</a></p>
   </div>
</div>

<?php $this->inlineScript()->captureStart() ?>
<?php $this->inlineScript()->captureEnd() ?>
