<?php
  $title = $this->translate('Register User');
  $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('member', array('action' => 'join')));
$form->prepare();

// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="control-group">
  <?php $first_name = $form->get('first_name'); ?>
  <?php echo $this->formLabel($first_name); ?>
  <div class="controls">
    <?php echo $this->formInput($first_name); ?>
    <?php echo $this->formElementErrors($first_name); ?>
  </div>
</div>

<div class="control-group">
<div class="controls">
<?php
echo $this->formRow($form->get('last_name'));
?></div></div>
<div class="control-group">
<div class="controls">
<?php
echo $this->formRow($form->get('email_address'));
?></div></div>
<div class="control-group">
<div class="controls">
<?php
echo $this->formRow($form->get('email_address_private'));
?></div></div>
<div class="control-group">
<div class="controls">
<?php
echo $this->formRow($form->get('password'));
?></div></div>
<div class="control-group">
<div class="controls">
<?php
echo $this->formRow($form->get('about'));
?></div></div>
<div class="control-group">
<div class="controls">
<?php
echo $this->formRow($form->get('interests'));
?></div></div>
<div class="control-group">
<div class="controls">
<?php
echo $this->formRow($form->get('captcha'));
?></div></div>
<?php 
echo $this->formElement($form->get('security')) 
?>
<?php
  echo $this->formSubmit($form->get('submit'));
  echo $this->form()->closeTag();
?>