<?php $count = 0 ?>
<?php foreach ($this->container as $page): ?>
    <ul class="nav <?php echo $page->getClass() ?>">    
        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li><a href="<?php echo $page->getHref() ?>">
                <?php echo $this->translate($page->getLabel()) ?>
            </a></li>
        <?php else: ?>
        	<li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span><?php echo $this->translate($page->getLabel()) ?></span><b class="caret"></b>
            </a>
            <ul class="dropdown-menu <?php echo $page->getClass() ?>" id="page_<?php echo $count ?>">
            <?php foreach($page->getPages() as $child): ?>
                <?php // when using partials we need to manually check for ACL conditions ?>
                <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                <li>
                    <a tabindex="-1" href="<?php echo $child->getHref() ?>">
                        <?php echo $this->translate($child->getLabel()) ?>
                    </a>
                </li>
            <?php endforeach ?>
            </ul>
            </li>
        <?php endif ?>
        <?php $count++ ?>
    </ul>        
<?php endforeach ?>