<?php 

/**
 * Main layout.
 *
 * @copyright  2012 iTradeTunes Inc.
 * @version    $Id$
 * @since      File available since release 1.0.0.0
 */

echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('iTradeTunes')) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/bootstrap.min.js') 
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('iTradeTunes') ?></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
          <?php $url = $this->url('member', array('action' => 'login')); ?>
          <form class="navbar-form pull-right" action="<?php echo $url; ?>" method="post">
            <input type="text" name="email" class="span2" placeholder=<?php echo $this->translate('Email') ?>>
            <input type="password" name="password" class="span2" placeholder=<?php echo $this->translate('Password') ?>>
            <button type="submit" name="submit" class="btn"><?php echo $this->translate('Sign in') ?></button>
          </form>
        </div>
      </div>
    </div>

    <div class="container">

      <!-- Display flash messages -->
      <?php if(count($this->flashMessages()) > 0) : ?>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <?php foreach ($this->flashMessages() as $message) : ?>
            <?php echo $this->escapeHTML($message); ?><br>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
      
      <?php echo $this->content; ?>
      <hr>
      <footer>
        <p>&copy; 2012 iTradeTunes Inc. <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>
    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
