<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>

<li class="disabled"><span>
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
&nbsp;of <?php echo $this->totalItemCount; ?></span>
</li>

<!-- First page link -->
<?php if (isset($this->previous)): ?>
<li>
  <a href="<?php echo $this->url($this->route, array('page' => $this->first)); ?>">
    &laquo;
  </a> </li>
<?php else: ?>
  <li class="disabled"><span>&laquo;</span></li>
<?php endif; ?>




<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<li>
  <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
    &lsaquo;
  </a></li>
<?php else: ?>
  <li class="disabled"><span>&lsaquo;</span></li>
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li>
  <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
    &rsaquo;
  </a> </li>
<?php else: ?>
  <li class="disabled"><span>&rsaquo;</span></li>
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
<li>
  <a href="<?php echo $this->url($this->route, array('page' => $this->last)); ?>">
    &raquo;
  </a></li>
<?php else: ?>
  <li class="disabled"><span>&raquo;</span></li>
<?php endif; ?>


</ul>
</div>
<?php endif; ?>

