<?php 

/**
 * Trade layout.
 *
 * @copyright  2012 iTradeTunes Inc.
 * @version    $Id$
 * @since      File available since release 1.0.0.0
 */

echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('iTradeTunes')) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/bootstrap.min.js') 
                                  ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js') ?>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('iTradeTunes') ?></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
              </ul>
          </div><!--/.nav-collapse -->

          <!-- Member dropdown -->
          <?php $sm = $this->getHelperPluginManager()->getServiceLocator(); 
                $auth = $sm->get('auth'); ?>
          <ul class="nav pull-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $auth->getIdentity(); ?><b class="caret"></b></a>
              <ul class="dropdown-menu pull-right">
                <li><a tabindex="-1" href="<?php echo $this->url('member', array('action' => 'logout')) ?>"><?php echo $this->translate('Log Out') ?></a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <!-- Display flash messages -->
      <?php if(count($this->flashMessages()) > 0) : ?>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <?php foreach ($this->flashMessages() as $message) : ?>
            <?php echo $this->escapeHTML($message); ?><br>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
      
      <?php echo $this->content; ?>
      <hr>
      <footer>
        <p>&copy; 2012 iTradeTunes Inc. <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>
    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
