<?php 

/**
 * Trade layout.
 *
 * @copyright  2012 iTradeTunes Inc.
 * @version    $Id$
 * @since      File available since release 1.0.0.0
 */

echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('iTradeTunes')) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/bootstrap.min.js') 
                                  ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js') ?>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('iTradeTunes') ?></a>
          <div class="nav-collapse">
            <?php $sm = $this->getHelperPluginManager()->getServiceLocator(); 
                  $auth = $sm->get('auth');
                  $partial = array('partial/menu.phtml', 'default');
		          $this->navigation('navigation')->menu()->setPartial($partial);
		          // Replace navigation labels
		          $this->navigation('navigation')->findOneByLabel('<identity>')->setLabel($auth->getIdentity());
		          $this->navigation('navigation')->menu()->setPartial($partial);
		          echo $this->navigation('navigation')->menu()->render() ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <!-- Display error flash messages -->
      <?php $messages = $this->flashMessages()->errorMessages();
            if(count($messages) > 0) :
              echo $this->partial('partial/message.phtml', array('messages' => $messages, 'class' => 'alert-error'));
            endif; ?>

      <!-- Display flash messages -->
      <?php $messages = $this->flashMessages()->messages();
            if(count($messages) > 0) :
              echo $this->partial('partial/message.phtml', array('messages' => $messages, 'class' => 'alert-block'));
            endif; ?>
                  
      <!-- Display info flash messages -->
      <?php $messages = $this->flashMessages()->infoMessages();
            if(count($messages) > 0) :
              echo $this->partial('partial/message.phtml', array('messages' => $messages, 'class' => 'alert-info'));
            endif; ?>
      
      <!-- Display success flash messages -->
      <?php $messages = $this->flashMessages()->successMessages();
            if(count($messages) > 0) :
              echo $this->partial('partial/message.phtml', array('messages' => $messages, 'class' => 'alert-success'));
            endif; ?>
              
      <?php echo $this->content; ?>
      <hr>
      <footer>
        <p>&copy; 2012 iTradeTunes Inc. <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>
    </div> <!-- /container -->

  <?php $this->inlineScript()->captureStart() ?>
    $('.with-tooltip').tooltip()
  <?php $this->inlineScript()->captureEnd() ?> 
    
  <?php echo $this->inlineScript() ?>
  </body>
</html>
